"use strict";
/* ============ profile.js — Profile hub: full port of the iOS Profile feature ============
 *
 * Matches the app's UserProfile model (UserProfile.swift) and ProfileView.swift
 * sections. Sections:
 *   1. Account      — photo, first/last name, username (+ copy), nickname,
 *                      department, backup status, sign out
 *   2. Commission   — per-department tier tables: view/edit tiers, special
 *                      rates, reset to defaults
 *   3. Tax          — home state (CA gates the estimate), income-tax
 *                      estimate %, California payroll breakdown, preview
 *   4. Reminders    — LINK card to Schedule → Reminders (no duplication;
 *                      the editors live in schedule.js)
 *   5. Home layout  — widget show/hide + reorder (homeWidgetOrder /
 *                      homeWidgetsOff), reset to the app's default order
 *
 * DELIBERATELY EXCLUDED: the Buddy AI / provider settings. Those live in
 * settings.js (server-only dashboard AI config) and must not be touched here.
 * There is no iOS AI option on the dashboard — the user was explicit.
 *
 * WIRING (parent adds to dashboard.html — do NOT edit this file):
 *   <script src="/profile.js"></script>   (after sync.js / payengine.js)
 *   Add a Profile tab button (desktop bar + mobile nav) with data-tab="profile"
 *   Add a panel container: <div id="profile-body"> in the profile tab pane
 *   In loadTab's map:  profile: loadProfile
 *   async function loadProfile() { await ProfileUI.open(document.getElementById("profile-body")); }
 *
 * Sync: all mutations go through SyncEngine.queueWrite with the EXISTING
 *   updateProfile op: { type:"updateProfile", updates:{ name, nickname,
 *   username, profilePhoto, department, commissionTables, state,
 *   incomeTaxEstimate, homeWidgetOrder, homeWidgetsOff } }
 * No new sync ops are needed.
 *
 * Depends on globals from dashboard.html: $, esc, money, spinner,
 * showError, SyncEngine, SupaClient (sign-out email), PayEngine (tax math).
 */
const ProfileUI = (() => {
  // ---- App constants -------------------------------------------------------
  const DEPARTMENTS = [
    { id: "gsa",       title: "GSA",       subtitle: "General Sales Associate" },
    { id: "systems",   title: "Systems",   subtitle: "PC Systems" },
    { id: "byo",       title: "BYO",       subtitle: "Build Your Own" },
    { id: "ce",        title: "CE",        subtitle: "Consumer Electronics" },
    { id: "warehouse", title: "Warehouse", subtitle: "Warehouse" },
  ];
  const CONFIRMED_RATES = ["gsa", "ce"]; // Department.hasConfirmedRates

  // HomeWidget (HomeLayout.swift) — title, subtitle, default order.
  const HOME_WIDGETS = [
    { id: "goal",           title: "Goal",                subtitle: "Your active sales goal and progress" },
    { id: "payPeriod",      title: "Pay period",          subtitle: "This period's est. take-home and pre-tax pay" },
    { id: "monthSoFar",     title: "Month so far",        subtitle: "Top items, brands, plans, and biggest sale" },
    { id: "commissionMonth",title: "Commission this month",subtitle: "Commission total and per-hour this month" },
    { id: "topDays",        title: "Top 5 days",          subtitle: "Your five best days, ranked by commission" },
  ];
  const DEFAULT_WIDGET_ORDER = HOME_WIDGETS.map(w => w.id);

  // GSA defaults — CommissionTable.gsa (CommissionTable.swift:49-58),
  // identical to CE. Every other department starts here (default(for:)).
  function gsaDefaults() {
    return {
      tiers: [
        { minPrice: 0,   maxPrice: 9.99,  rate: 0.12 },
        { minPrice: 10,  maxPrice: 99.99, rate: 0.06 },
        { minPrice: 100, maxPrice: 199.99,rate: 0.03 },
        { minPrice: 200, maxPrice: null,   rate: 0.02 }, // null = "and up"
      ],
      outOfDepartmentRate: 0.01,
      servicePlanRate: 0.10,
    };
  }

  const US_STATES = [
    ["AL","Alabama"],["AK","Alaska"],["AZ","Arizona"],["AR","Arkansas"],["CA","California"],
    ["CO","Colorado"],["CT","Connecticut"],["DE","Delaware"],["FL","Florida"],["GA","Georgia"],
    ["HI","Hawaii"],["ID","Idaho"],["IL","Illinois"],["IN","Indiana"],["IA","Iowa"],
    ["KS","Kansas"],["KY","Kentucky"],["LA","Louisiana"],["ME","Maine"],["MD","Maryland"],
    ["MA","Massachusetts"],["MI","Michigan"],["MN","Minnesota"],["MS","Mississippi"],["MO","Missouri"],
    ["MT","Montana"],["NE","Nebraska"],["NV","Nevada"],["NH","New Hampshire"],["NJ","New Jersey"],
    ["NM","New Mexico"],["NY","New York"],["NC","North Carolina"],["ND","North Dakota"],["OH","Ohio"],
    ["OK","Oklahoma"],["OR","Oregon"],["PA","Pennsylvania"],["RI","Rhode Island"],["SC","South Carolina"],
    ["SD","South Dakota"],["TN","Tennessee"],["TX","Texas"],["UT","Utah"],["VT","Vermont"],
    ["VA","Virginia"],["WA","Washington"],["WV","West Virginia"],["WI","Wisconsin"],["WY","Wyoming"],
  ];

  // ---- State ----------------------------------------------------------------
  let box = null;
  let profile = {};
  let commDept = "gsa";   // which department's table is being edited
  let commDraft = null;   // working copy of the table
  let saveTimer = null;

  // ---- Helpers ---------------------------------------------------------------
  function deptTitle(id) {
    const d = DEPARTMENTS.find(x => x.id === id);
    return d ? d.title : id;
  }
  function getProfile(backup) {
    return (backup && backup.data && backup.data.profile) || {};
  }
  function splitName(full) {
    const parts = String(full || "").trim().split(/\s+/);
    if (!parts.length || !parts[0]) return { first: "", last: "" };
    return { first: parts[0], last: parts.slice(1).join(" ") };
  }
  function sessionEmail() {
    try { return (SupaClient.getSession() || {}).email || ""; } catch (e) { return ""; }
  }
  function photoData() {
    // Mirrors the app's account.profile?.profilePhoto (base64 data URL).
    return profile.profilePhoto || profile.photo || "";
  }
  function widgetState() {
    // Effective ordered list of VISIBLE widget ids.
    const order = (profile.homeWidgetOrder && profile.homeWidgetOrder.length)
      ? profile.homeWidgetOrder.slice() : DEFAULT_WIDGET_ORDER.slice();
    const off = new Set(profile.homeWidgetsOff || []);
    const known = new Set(HOME_WIDGETS.map(w => w.id));
    // Keep saved order but drop unknown / off ids; append new defaults.
    let visible = order.filter(id => known.has(id) && !off.has(id));
    for (const w of HOME_WIDGETS) {
      if (!visible.includes(w.id) && !off.has(w.id)) visible.push(w.id);
    }
    return { visible, off };
  }
  async function saveProfile(updates, immediate) {
    Object.assign(profile, updates);
    const write = () => SyncEngine.queueWrite({ type: "updateProfile", updates }).catch(e => {
      showError("Couldn't save: " + (e.message || e));
    });
    if (immediate) return write();
    // Debounce rapid field edits so typing doesn't spam the queue.
    clearTimeout(saveTimer);
    return new Promise(resolve => {
      saveTimer = setTimeout(() => write().then(resolve, resolve), 600);
    });
  }
  function tierLabel(t) {
    const lo = "$" + Number(t.minPrice).toFixed(2);
    return (t.maxPrice === null || t.maxPrice === undefined)
      ? lo + " and up" : lo + " – $" + Number(t.maxPrice).toFixed(2);
  }

  // ---- Render: Account ---------------------------------------------------------
  function accountHTML() {
    const { first, last } = splitName(profile.name);
    const email = sessionEmail();
    const photo = photoData();
    const avatar = photo
      ? '<img src="' + esc(photo) + '" class="pf-avatar" alt="Profile photo">'
      : '<div class="pf-avatar pf-avatar-empty">👤</div>';
    const username = profile.username || "";
    return (
      '<div class="section-title">Account</div>' +
      '<div class="panel">' +
        '<div class="pf-identity">' +
          '<div class="pf-photo-wrap">' + avatar +
            '<label class="pf-photo-btn" title="Change photo">📷<input type="file" id="pf-photo" accept="image/*" hidden></label>' +
          "</div>" +
          '<div class="pf-identity-main">' +
            '<div class="pf-name">' + esc(profile.name || "Your name") + "</div>" +
            (username ? '<button class="link-btn pf-username" id="pf-username-copy" title="Copy username">@' + esc(username) + "</button>" : "") +
            '<div class="li-sub">' + esc(deptTitle(profile.department || "gsa")) + "</div>" +
          "</div>" +
        "</div>" +
        '<div class="field-row"><label>First name</label>' +
          '<input type="text" id="pf-first" value="' + esc(first) + '" placeholder="Christian" autocomplete="given-name"></div>' +
        '<div class="field-row"><label>Last name</label>' +
          '<input type="text" id="pf-last" value="' + esc(last) + '" placeholder="Ortiz" autocomplete="family-name"></div>' +
        '<div class="field-row"><label>Username</label>' +
          '<input type="text" id="pf-username" value="' + esc(username) + '" placeholder="salesfloor.sam" autocomplete="off" spellcheck="false">' +
          '<div class="hint">Your handle in Micro Buddy. Letters, numbers, _ and . only, 3–20 characters.</div></div>' +
        '<div class="field-row"><label>Nickname</label>' +
          '<input type="text" id="pf-nick" value="' + esc(profile.nickname || "") + '" placeholder="What Buddy calls you" autocomplete="off">' +
          '<div class="hint">Defaults to your first name.</div></div>' +
        '<div class="field-row"><label>Department</label>' +
          '<select id="pf-dept">' +
            DEPARTMENTS.map(d => '<option value="' + d.id + '"' +
              ((profile.department || "gsa") === d.id ? " selected" : "") + ">" +
              esc(d.title) + " — " + esc(d.subtitle) + "</option>").join("") +
          "</select>" +
          '<div class="hint">Your home department. Sales in other departments pay the out-of-department rate.</div></div>' +
      "</div>" +
      '<div class="panel">' +
        '<div class="list-item"><div class="li-main">Signed in<div class="li-sub">' +
          esc(email || "Email not available") + "</div></div>" +
          '<span class="pill green">Paired</span></div>' +
        '<div class="list-item" style="border:none"><div class="li-main">Sign out<div class="li-sub">This device only — your phone stays paired.</div></div>' +
          '<button class="btn ghost" id="pf-signout">Sign out</button></div>' +
      "</div>"
    );
  }

  function bindAccount() {
    const first = box.querySelector("#pf-first"), last = box.querySelector("#pf-last");
    const commitName = () => {
      const n = (first.value + " " + last.value).trim().replace(/\s+/g, " ");
      saveProfile({ name: n });
      const nameEl = box.querySelector(".pf-name");
      if (nameEl) nameEl.textContent = n || "Your name";
    };
    ["change", "blur"].forEach(ev => { first.addEventListener(ev, commitName); last.addEventListener(ev, commitName); });

    box.querySelector("#pf-username").addEventListener("change", (e) => {
      const v = e.target.value.trim();
      if (v && !/^[A-Za-z0-9_.]{3,20}$/.test(v)) {
        showError("Username must be 3–20 characters: letters, numbers, _ and .");
        e.target.value = profile.username || "";
        return;
      }
      saveProfile({ username: v });
    });

    box.querySelector("#pf-nick").addEventListener("change", (e) =>
      saveProfile({ nickname: e.target.value.trim() }));

    box.querySelector("#pf-dept").addEventListener("change", (e) => {
      saveProfile({ department: e.target.value }, true).then(() => {
        // Commission editor shows the current department's table by default.
        commDept = e.target.value;
        refreshCommissionSection();
        const sub = box.querySelector(".pf-identity-main .li-sub");
        if (sub) sub.textContent = deptTitle(e.target.value);
      });
    });

    const copyBtn = box.querySelector("#pf-username-copy");
    if (copyBtn) copyBtn.addEventListener("click", async () => {
      const u = "@" + (profile.username || "");
      try {
        await navigator.clipboard.writeText(u);
        copyBtn.textContent = "Copied ✓";
        setTimeout(() => { copyBtn.textContent = u; }, 1500);
      } catch (e) { showError("Couldn't copy"); }
    });

    box.querySelector("#pf-photo").addEventListener("change", (e) => {
      const f = e.target.files && e.target.files[0];
      if (!f) return;
      const img = new Image();
      const url = URL.createObjectURL(f);
      img.onload = () => {
        URL.revokeObjectURL(url);
        const size = 256;
        const canvas = document.createElement("canvas");
        canvas.width = size; canvas.height = size;
        const ctx = canvas.getContext("2d");
        const side = Math.min(img.width, img.height);
        ctx.drawImage(img, (img.width - side) / 2, (img.height - side) / 2, side, side, 0, 0, size, size);
        const dataUrl = canvas.toDataURL("image/jpeg", 0.85);
        saveProfile({ profilePhoto: dataUrl }, true).then(() => {
          const wrap = box.querySelector(".pf-photo-wrap");
          if (wrap) {
            const imgEl = document.createElement("img");
            imgEl.src = dataUrl; imgEl.className = "pf-avatar"; imgEl.alt = "Profile photo";
            const old = wrap.querySelector(".pf-avatar");
            if (old) old.replaceWith(imgEl);
          }
          // Refresh the header avatar too.
          if (window.updateSettingsAvatar) window.updateSettingsAvatar().catch(() => {});
        });
      };
      img.onerror = () => { URL.revokeObjectURL(url); showError("Couldn't read that image."); };
      img.src = url;
    });

    box.querySelector("#pf-signout").addEventListener("click", async () => {
      if (!confirm("Sign out of Micro Buddy on this device?")) return;
      try { await fetch("/logout"); } catch (e) {}
      location.reload();
    });
  }

  // ---- Render: Commission ---------------------------------------------------------
  function tableFor(dept) {
    const tables = profile.commissionTables || {};
    const t = tables[dept] || gsaDefaults();
    return {
      tiers: (t.tiers || []).map(x => ({
        minPrice: Number(x.minPrice) || 0,
        maxPrice: (x.maxPrice === null || x.maxPrice === undefined) ? null : Number(x.maxPrice),
        rate: Number(x.rate) || 0,
      })),
      outOfDepartmentRate: Number(t.outOfDepartmentRate) || 0,
      servicePlanRate: Number(t.servicePlanRate) || 0,
    };
  }

  function commissionHTML() {
    const t = commDraft;
    const rows = t.tiers.map((tier, i) =>
      '<div class="comm-tier" data-i="' + i + '">' +
        '<input type="number" min="0" step="0.01" data-f="minPrice" value="' + tier.minPrice + '" title="Min price">' +
        '<span class="comm-dash">–</span>' +
        (tier.maxPrice === null
          ? '<span class="comm-andup">and up</span><button class="link-btn" data-setmax="' + i + '">set max</button>'
          : '<input type="number" min="0" step="0.01" data-f="maxPrice" value="' + tier.maxPrice + '" title="Max price">') +
        '<input type="number" min="0" max="100" step="0.1" data-f="rate" value="' + (tier.rate * 100).toFixed(1) + '" title="Rate %"><span class="comm-pct">%</span>' +
        '<button class="icon-btn" data-deltier="' + i + '" title="Remove tier">✕</button>' +
      "</div>"
    ).join("");
    return (
      '<div class="section-title">Commission rates</div>' +
      '<div class="panel" id="pf-comm-panel">' +
        '<div class="field-row"><label>Department</label><div class="seg-pills">' +
          DEPARTMENTS.map(d =>
            '<button class="seg-pill' + (commDept === d.id ? " selected" : "") +
            '" data-comm-dept="' + d.id + '">' + esc(d.title) + "</button>"
          ).join("") +
        "</div></div>" +
        (CONFIRMED_RATES.includes(commDept)
          ? '<div class="hint" style="margin-bottom:8px">Confirmed rates for ' + esc(deptTitle(commDept)) + ". Edits sync to your phone.</div>"
          : '<div class="warn-inline">' + esc(deptTitle(commDept)) + ' runs the GSA table until its own rates are confirmed. ' +
            "These are fully editable here until the real numbers are known.</div>") +
        '<div class="comm-head"><span>Price range</span><span>Rate</span></div>' +
        rows +
        '<div class="btn-row"><button class="btn ghost sm" id="pf-add-tier">＋ Add tier</button>' +
        '<button class="btn ghost sm" id="pf-reset-table">Reset to defaults</button></div>' +
        '<div class="section-title" style="margin-top:14px">Special rates</div>' +
        '<div class="field-row"><label>Out-of-department sales</label>' +
          '<div class="pct-wrap"><input type="number" min="0" max="100" step="0.1" id="pf-ood" value="' +
          (t.outOfDepartmentRate * 100).toFixed(1) + '"><span>%</span></div></div>' +
        '<div class="field-row"><label>Service plans</label>' +
          '<div class="pct-wrap"><input type="number" min="0" max="100" step="0.1" id="pf-sp" value="' +
          (t.servicePlanRate * 100).toFixed(1) + '"><span>%</span></div></div>' +
        '<div class="btn-row"><button class="btn" id="pf-save-table">Save ' + esc(deptTitle(commDept)) + ' table</button>' +
        '<span id="pf-comm-status" class="form-status"></span></div>' +
      "</div>"
    );
  }

  function refreshCommissionSection() {
    commDraft = tableFor(commDept);
    const panel = box.querySelector("#pf-comm-panel");
    if (panel) {
      panel.outerHTML = commissionHTML();
      bindCommission();
    }
  }

  function bindCommission() {
    box.querySelectorAll("[data-comm-dept]").forEach(btn => {
      btn.addEventListener("click", () => { commDept = btn.dataset.commDept; refreshCommissionSection(); });
    });
    box.querySelectorAll(".comm-tier input[data-f]").forEach(inp => {
      inp.addEventListener("change", () => {
        const row = inp.closest(".comm-tier");
        const i = Number(row.dataset.i);
        const f = inp.dataset.f;
        let v = parseFloat(inp.value);
        if (isNaN(v)) v = 0;
        if (f === "rate") v = v / 100;
        commDraft.tiers[i][f] = v;
      });
    });
    box.querySelectorAll("[data-setmax]").forEach(btn => {
      btn.addEventListener("click", () => {
        const i = Number(btn.dataset.setmax);
        const cur = commDraft.tiers[i];
        cur.maxPrice = (cur.minPrice || 0) + 0.01;
        refreshCommissionSection();
      });
    });
    box.querySelectorAll("[data-deltier]").forEach(btn => {
      btn.addEventListener("click", () => {
        commDraft.tiers.splice(Number(btn.dataset.deltier), 1);
        refreshCommissionSection();
      });
    });
    box.querySelector("#pf-add-tier").addEventListener("click", () => {
      const tiers = commDraft.tiers;
      const top = tiers.length ? tiers[tiers.length - 1] : null;
      const min = top && top.maxPrice !== null ? top.maxPrice : (top ? top.minPrice + 100 : 0);
      tiers.push({ minPrice: min, maxPrice: null, rate: 0.02 });
      refreshCommissionSection();
    });
    box.querySelector("#pf-reset-table").addEventListener("click", () => {
      if (!confirm("Reset the " + deptTitle(commDept) + " table to the default GSA rates?")) return;
      commDraft = gsaDefaults();
      saveTable(true);
    });
    box.querySelector("#pf-save-table").addEventListener("click", () => saveTable(false));
  }

  async function saveTable(silent) {
    const status = box.querySelector("#pf-comm-status");
    // Validate: tiers sorted, non-overlapping, at least one "and up".
    const tiers = commDraft.tiers.slice().sort((a, b) => a.minPrice - b.minPrice);
    commDraft.tiers = tiers;
    const ood = clampPct(box.querySelector("#pf-ood").value);
    const sp = clampPct(box.querySelector("#pf-sp").value);
    commDraft.outOfDepartmentRate = ood / 100;
    commDraft.servicePlanRate = sp / 100;
    if (!tiers.length) { showError("Add at least one tier."); return; }
    const hasOpen = tiers.some(t => t.maxPrice === null);
    if (!hasOpen) {
      // App behavior: the top tier is open-ended ("and up").
      tiers[tiers.length - 1].maxPrice = null;
    }
    for (const t of tiers) {
      if (t.maxPrice !== null && t.maxPrice <= t.minPrice) {
        showError("A tier's max must be above its min (" + tierLabel(t) + ").");
        return;
      }
    }
    const tables = Object.assign({}, profile.commissionTables);
    tables[commDept] = commDraft;
    if (status) { status.textContent = "Saving…"; status.className = "form-status"; }
    try {
      await saveProfile({ commissionTables: tables }, true);
      if (status) { status.textContent = "Saved ✓"; status.className = "form-status ok"; }
    } catch (e) {
      if (status) { status.textContent = "Save failed"; status.className = "form-status err"; }
    }
    refreshCommissionSection();
  }
  function clampPct(v) {
    let n = parseFloat(v);
    if (isNaN(n)) return 0;
    return Math.min(100, Math.max(0, n));
  }

  // ---- Render: Tax ----------------------------------------------------------------
  function taxHTML() {
    const state = profile.state || "";
    const pct = ((profile.incomeTaxEstimate !== undefined && profile.incomeTaxEstimate !== null)
      ? profile.incomeTaxEstimate * 100 : 10.5);
    const isCA = state === "CA";
    // CaliforniaTaxes.swift 2026 estimates.
    const SS = 6.2, MED = 1.45, SDI = 1.3;
    const example = 1000;
    const breakdown = isCA ? PayEngine.taxBreakdown(example, pct / 100) : null;
    return (
      '<div class="section-title">Tax settings</div>' +
      '<div class="panel">' +
        '<div class="field-row"><label>Home state</label>' +
          '<select id="pf-state">' +
            '<option value="">Choose…</option>' +
            US_STATES.map(s => '<option value="' + s[0] + '"' + (state === s[0] ? " selected" : "") + ">" +
              esc(s[1]) + "</option>").join("") +
          "</select>" +
          '<div class="hint">Take-home estimates are only shown for California (the state ' +
          "the app has payroll numbers for).</div></div>" +
        '<div class="field-row"><label>Income tax estimate</label>' +
          '<div class="pct-wrap"><input type="number" min="0" max="40" step="0.5" id="pf-taxrate" value="' +
          pct.toFixed(1) + '"><span>%</span></div>' +
          '<div class="hint">Combined federal + CA income-tax estimate (default 10.5%). Clamped 0–40%.</div></div>' +
        (isCA
          ? '<div class="section-title" style="margin-top:10px">California payroll, 2026</div>' +
            '<div class="list-item"><div class="li-main">Social Security</div><div class="li-val">' + SS.toFixed(2) + "%</div></div>" +
            '<div class="list-item"><div class="li-main">Medicare</div><div class="li-val">' + MED.toFixed(2) + "%</div></div>" +
            '<div class="list-item"><div class="li-main">CA SDI</div><div class="li-val">' + SDI.toFixed(2) + "%</div></div>" +
            '<div class="list-item"><div class="li-main">Income tax (your estimate)</div><div class="li-val">' + pct.toFixed(1) + "%</div></div>" +
            (breakdown
              ? '<div class="tax-example">On a <b>' + money(example) + '</b> paycheck: take-home ≈ <b class="pos">' +
                money(breakdown.net) + "</b> (" + money(breakdown.totalTaxes) + " in taxes)</div>"
              : "") +
            '<div class="hint" style="margin-top:8px">Estimate only — your actual withholding may differ.</div>'
          : '<div class="hint">Set your home state to California to see the CA payroll breakdown ' +
            "and estimated take-home.</div>") +
      "</div>"
    );
  }

  function bindTax() {
    box.querySelector("#pf-state").addEventListener("change", (e) => {
      saveProfile({ state: e.target.value }, true).then(() => {
        const panel = box.querySelector("#pf-tax-panel");
        if (panel) { panel.outerHTML = '<div id="pf-tax-panel">' + taxHTML() + "</div>"; bindTax(); }
      });
    });
    const rateInput = box.querySelector("#pf-taxrate");
    rateInput.addEventListener("change", () => {
      let v = parseFloat(rateInput.value);
      if (isNaN(v)) v = 10.5;
      // Mirrors CATaxEstimate.clampIncomeTax: 0–40%.
      v = Math.min(40, Math.max(0, v));
      rateInput.value = v.toFixed(1);
      saveProfile({ incomeTaxEstimate: v / 100 }, true).then(() => {
        const panel = box.querySelector("#pf-tax-panel");
        if (panel) { panel.outerHTML = '<div id="pf-tax-panel">' + taxHTML() + "</div>"; bindTax(); }
      });
    });
  }

  // ---- Render: Reminders link --------------------------------------------------------
  function remindersHTML() {
    return (
      '<div class="section-title">Reminders</div>' +
      '<div class="panel">' +
        '<div class="list-item" style="border:none">' +
          '<div class="li-main">Notification reminders<div class="li-sub">Leave-for-work, shift start, log-your-sales, payday recap, weekly nudge — all live in Schedule.</div></div>' +
          '<button class="btn" id="pf-go-reminders">Open reminders</button>' +
        "</div>" +
      "</div>"
    );
  }

  function bindRemindersLink() {
    const btn = box.querySelector("#pf-go-reminders");
    if (!btn) return;
    btn.addEventListener("click", () => {
      // Jump to the Schedule tab, then scroll to the reminders panel.
      const tabBtn = document.querySelector('.tab-btn[data-tab="schedule"], .bottom-nav button[data-tab="schedule"]');
      if (tabBtn) tabBtn.click();
      setTimeout(() => {
        const el = document.getElementById("rem-save");
        if (el) el.scrollIntoView({ behavior: "smooth", block: "center" });
      }, 400);
    });
  }

  // ---- Render: Home layout --------------------------------------------------------------
  function layoutHTML() {
    const { visible, off } = widgetState();
    const hidden = HOME_WIDGETS.filter(w => off.has(w.id));
    const rowHTML = (w, idx, total) =>
      '<div class="widget-row" data-w="' + w.id + '">' +
        '<span class="widget-grip">☰</span>' +
        '<div class="li-main">' + esc(w.title) + '<div class="li-sub">' + esc(w.subtitle) + "</div></div>" +
        (idx > 0 ? '<button class="icon-btn" data-wup="' + idx + '" title="Move up">▲</button>' : '<span class="icon-btn ph"></span>') +
        (idx < total - 1 ? '<button class="icon-btn" data-wdown="' + idx + '" title="Move down">▼</button>' : '<span class="icon-btn ph"></span>') +
        '<button class="icon-btn" data-whide="' + w.id + '" title="Hide">👁️‍🗨️</button>' +
      "</div>";
    return (
      '<div class="section-title">Home layout</div>' +
      '<div class="panel">' +
        '<div class="li-sub" style="margin-bottom:8px">Reorder and hide widgets on your Home page. ' +
        "The greeting, payday recap, and your photo stay fixed.</div>" +
        visible.map((id, i) => {
          const w = HOME_WIDGETS.find(x => x.id === id);
          return rowHTML(w, i, visible.length);
        }).join("") +
        (hidden.length
          ? '<div class="section-title" style="margin-top:10px">Hidden</div>' +
            hidden.map(w =>
              '<div class="widget-row dimmed"><div class="li-main">' + esc(w.title) + "</div>" +
              '<button class="btn ghost sm" data-wshow="' + w.id + '">Show</button></div>'
            ).join("")
          : "") +
        '<div class="btn-row"><button class="btn ghost sm" id="pf-layout-reset">Reset to default</button></div>' +
      "</div>"
    );
  }

  function bindLayout() {
    const { visible, off } = widgetState();
    async function persist(newVisible, newOff) {
      await saveProfile({
        homeWidgetOrder: newVisible,
        homeWidgetsOff: Array.from(newOff),
      }, true);
      const panel = box.querySelector("#pf-layout-panel");
      if (panel) { panel.outerHTML = '<div id="pf-layout-panel">' + layoutHTML() + "</div>"; bindLayout(); }
    }
    box.querySelectorAll("[data-wup]").forEach(b => b.addEventListener("click", () => {
      const i = Number(b.dataset.wup);
      if (i <= 0) return;
      const v = visible.slice();
      [v[i - 1], v[i]] = [v[i], v[i - 1]];
      persist(v, off);
    }));
    box.querySelectorAll("[data-wdown]").forEach(b => b.addEventListener("click", () => {
      const i = Number(b.dataset.wdown);
      const v = visible.slice();
      if (i >= v.length - 1) return;
      [v[i + 1], v[i]] = [v[i], v[i + 1]];
      persist(v, off);
    }));
    box.querySelectorAll("[data-whide]").forEach(b => b.addEventListener("click", () => {
      const id = b.dataset.whide;
      const newOff = new Set(off); newOff.add(id);
      persist(visible.filter(x => x !== id), newOff);
    }));
    box.querySelectorAll("[data-wshow]").forEach(b => b.addEventListener("click", () => {
      const id = b.dataset.wshow;
      const newOff = new Set(off); newOff.delete(id);
      const v = visible.slice(); v.push(id);
      persist(v, newOff);
    }));
    box.querySelector("#pf-layout-reset").addEventListener("click", () => {
      persist(DEFAULT_WIDGET_ORDER.slice(), new Set());
    });
  }

  // ---- Styles (module-local, theme-token based) ---------------------------------------------
  function injectStyles() {
    if (document.getElementById("profile-ui-style")) return;
    const css = `
      .pf-identity { display:flex; gap:14px; align-items:center; margin-bottom:12px; }
      .pf-avatar { width:56px; height:56px; border-radius:50%; object-fit:cover; display:block; }
      .pf-avatar-empty { display:flex; align-items:center; justify-content:center; font-size:34px;
        background:var(--surface-high, #eee); }
      .pf-photo-wrap { position:relative; flex:none; }
      .pf-photo-btn { position:absolute; right:-4px; bottom:-4px; width:24px; height:24px; border-radius:50%;
        background:var(--surface-high, #eee); display:flex; align-items:center; justify-content:center;
        font-size:13px; cursor:pointer; border:1px solid var(--hairline, #ccc); }
      .pf-name { font-weight:700; font-size:1.1rem; }
      .pf-username { font-size:.85rem; padding:0; }
      .seg-pills { display:flex; gap:6px; flex-wrap:wrap; }
      .seg-pill { padding:6px 12px; border-radius:999px; border:1px solid var(--hairline, #ccc);
        background:transparent; color:var(--text-primary); cursor:pointer; font-size:.85rem; }
      .seg-pill.selected { background:var(--accent, #007aff); color:#fff; border-color:transparent; }
      .comm-head { display:flex; justify-content:space-between; font-size:.75rem; color:var(--text-secondary);
        margin:8px 0 4px; }
      .comm-tier { display:flex; align-items:center; gap:6px; margin-bottom:6px; }
      .comm-tier input[type=number] { width:76px; padding:6px 8px; border:1px solid var(--hairline, #ccc);
        border-radius:8px; background:var(--surface, #fff); color:var(--text-primary); }
      .comm-dash, .comm-pct { color:var(--text-secondary); font-size:.85rem; }
      .comm-andup { font-size:.85rem; color:var(--text-secondary); font-style:italic; min-width:56px; }
      .icon-btn { background:transparent; border:none; cursor:pointer; color:var(--text-secondary); font-size:.9rem;
        padding:4px 6px; border-radius:6px; }
      .icon-btn:hover { background:var(--surface-high, #eee); }
      .icon-btn.ph { visibility:hidden; }
      .pct-wrap { display:flex; align-items:center; gap:6px; }
      .pct-wrap input { width:80px; padding:6px 8px; border:1px solid var(--hairline, #ccc); border-radius:8px;
        background:var(--surface, #fff); color:var(--text-primary); }
      .warn-inline { background:color-mix(in srgb, var(--amber, #f59e0b) 12%, transparent);
        border:1px solid var(--amber, #f59e0b); border-radius:8px; padding:8px 10px; font-size:.85rem;
        color:var(--text-primary); margin-bottom:8px; }
      .tax-example { background:var(--surface-high, #f3f4f6); border-radius:8px; padding:8px 10px;
        font-size:.9rem; margin-top:8px; }
      .tax-example .pos { color:var(--green, #16a34a); }
      .widget-row { display:flex; align-items:center; gap:8px; padding:8px 0;
        border-bottom:1px solid var(--hairline, #eee); }
      .widget-row:last-of-type { border-bottom:none; }
      .widget-row .li-main { flex:1; }
      .widget-row.dimmed { opacity:.6; }
      .widget-grip { color:var(--text-secondary); cursor:grab; }
      .pill.green { background:var(--mint, #d1fae5); color:#065f46; font-size:.75rem; padding:2px 10px;
        border-radius:999px; font-weight:600; }
    `;
    const style = document.createElement("style");
    style.id = "profile-ui-style";
    style.textContent = css;
    document.head.appendChild(style);
  }

  // ---- Entry ---------------------------------------------------------------------------------
  async function open(container) {
    box = container || document.getElementById("profile-body");
    if (!box) throw new Error("ProfileUI.open: no container");
    injectStyles();
    box.innerHTML = spinner("Loading profile…");
    try {
      const backup = await SyncEngine.getLocalBackup();
      profile = getProfile(backup);
      commDept = profile.department || "gsa";
      commDraft = tableFor(commDept);
    } catch (e) {
      box.innerHTML = '<div class="panel">Couldn\'t load your profile: ' + esc(e.message || e) + "</div>";
      return;
    }
    box.innerHTML =
      accountHTML() +
      '<div id="pf-comm-panel">' + commissionHTML() + "</div>" +
      '<div id="pf-tax-panel">' + taxHTML() + "</div>" +
      remindersHTML() +
      '<div id="pf-layout-panel">' + layoutHTML() + "</div>";
    bindAccount();
    bindCommission();
    bindTax();
    bindRemindersLink();
    bindLayout();
  }

  return { open };
})();
